// Generates a blind clause set with Gemini from the taxonomy definitions only.
// The rule matcher is never tuned on this file; results are reported as-is.
import { writeFileSync } from 'node:fs';
import { CLAUSE_PATTERNS } from '../src/domain/clauses.ts';

const key = process.env.GEMINI_API_KEY;
if (!key) throw new Error('GEMINI_API_KEY missing');
const model = process.env.GEN_MODEL || 'gemini-2.5-pro';

async function ask(prompt: string): Promise<string[]> {
  const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json', 'x-goog-api-key': key! },
    body: JSON.stringify({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig: { temperature: 1, responseMimeType: 'application/json', responseSchema: { type: 'ARRAY', items: { type: 'STRING' } } },
    }),
  });
  if (!res.ok) throw new Error(`HTTP ${res.status} ${await res.text()}`);
  const data: any = await res.json();
  return JSON.parse(data.candidates[0].content.parts[0].text);
}

const rows: { text: string; label: string | null }[] = [];
for (const p of CLAUSE_PATTERNS) {
  const out = await ask(
    `Write 6 different special-term clauses (특약) as they might appear in real Korean jeonse lease contracts that match this description: "${p.definition}". ` +
      `Write 4 in Korean and 2 in English. Vary wording, sentence order, and formality; avoid reusing the same key phrases. Return a JSON array of strings only.`,
  );
  rows.push(...out.slice(0, 6).map((text) => ({ text, label: p.id })));
}
const neutral = await ask(
  'Write 18 realistic special-term clauses (특약) from Korean residential lease contracts that do NOT fit any of these categories: ' +
    CLAUSE_PATTERNS.map((p) => p.definition).join(' | ') +
    '. Include common topics (repairs, pets, management fees, restoration, options, early termination, parking, deposit guarantee cooperation, move-in date). 12 in Korean, 6 in English. Return a JSON array of strings only.',
);
rows.push(...neutral.slice(0, 18).map((text) => ({ text, label: null })));
writeFileSync(
  new URL('../tests/fixtures/clauses.blind.json', import.meta.url),
  JSON.stringify({ note: `Generated by ${model} on ${new Date().toISOString()} from taxonomy definitions only. Labels are the requested category. Never used to tune the rule matcher.`, rows }, null, 1),
);
console.log(`wrote ${rows.length} rows`);
